### ISSUE TITLE
Is it possible to accomplish something like "This Year"?

### ISSUE THREAD

**Issue by leandroz** [sonirico/datetoken.js#170]
With a year token it would become `now/y` but not sure how to do it with the current tokens.

**Comment by sonirico** [comment]
Hi! 

As of now, it is not implemented but PRs are welcome. It should be fairly straightforward to do it. In fact, the [python version](https://github.com/sonirico/datetoken.py/) already provides it.  Would you be willing to submit a PR?

**Comment by leandroz** [comment]
Hi!

I will take a look at both implementations and see what needs to be done :)
